
class XMLTable_4210():
    def __init__(self):
        self.xml1 = [
            { 'name': 'STT', 'align': 'center' },
            { 'name': 'MA_BN', 'align': 'right' },
            { 'name': 'HO_TEN', 'align': 'left' },
            { 'name': 'NGAY_SINH', 'align': 'center' },
            { 'name': 'GIOI_TINH', 'align': 'center' },
            { 'name': 'DIA_CHI', 'align': 'left' },
            { 'name': 'MA_THE', 'align': 'center' },
            { 'name': 'MA_DKBD', 'align': 'center' },
            { 'name': 'GT_THE_TU', 'align': 'center' },
            { 'name': 'GT.THE_DEN', 'align': 'center' },
            { 'name': 'MIEN_CUNG_CT', 'align': 'center' },
            { 'name': 'TEN_BENH', 'align': 'left' },
            { 'name': 'MA_BENH', 'align': 'left' },
            { 'name': 'MA_BENHKHAC', 'align': 'left' },
            { 'name': 'MA_LYDO_VVIEN', 'align': 'center' },
            { 'name': 'MA_NOI_CHUYEN', 'align': 'center' },
            { 'name': 'MA_TAI_NAN', 'align': 'center' },
            { 'name': 'NGAY_VAO', 'align': 'center' },
            { 'name': 'NGAY_RA', 'align': 'center' },
            { 'name': 'SO_NGAY_DTRI', 'align': 'center' },
            { 'name': 'KET_QUA_DTRI', 'align': 'center' },
            { 'name': 'TINH_TRANG_RV', 'align': 'center' },
            { 'name': 'NGAY_TTOAN', 'align': 'center' },
            { 'name': 'T_THUOC', 'align': 'right' },
            { 'name': 'T_VTYT', 'align': 'right' },
            { 'name': 'T_TONGCHI', 'align': 'right' },
            { 'name': 'T_BNTT', 'align': 'right' },
            { 'name': 'T_BNCCT', 'align': 'right' },
            { 'name': 'T_BHTT', 'align': 'right' },
            { 'name': 'T_NGUONKHAC', 'align': 'right' },
            { 'name': 'T_NGOAIDS', 'align': 'right' },
            { 'name': 'NAM_QT', 'align': 'center' },
            { 'name': 'THANG_QT', 'align': 'center' },
            { 'name': 'MA_LOAI_KCB', 'align': 'center' },
            { 'name': 'MA_KHOA', 'align': 'center' },
            { 'name': 'MA_CSKCB', 'align': 'center' },
            { 'name': 'MA_KHUVUC', 'align': 'center' },
            { 'name': 'MA_PTTT_QT', 'align': 'center' },
            { 'name': 'CAN_NANG', 'align': 'center' }
        ]
        
        self.xml2 = [
            { 'name': 'STT', 'align': 'center' },
            { 'name': 'MA_THUOC', 'align': 'left' },
            { 'name': 'MA_NHOM', 'align': 'center' },
            { 'name': 'TEN_THUOC', 'align': 'left' },
            { 'name': 'DON_VI_TINH', 'align': 'center' },
            { 'name': 'HAM_LUONG', 'align': 'left' },
            { 'name': 'DUONG_DUNG', 'align': 'center' },
            { 'name': 'LIEU_DUNG', 'align': 'left' },
            { 'name': 'SO_DANG_KY', 'align': 'left' },
            { 'name': 'TT_THAU', 'align': 'left' },
            { 'name': 'PHAM_Vl', 'align': 'center' },
            { 'name': 'TYLE_TT', 'align': 'center' },
            { 'name': 'SO_LUONG', 'align': 'left' },
            { 'name': 'DON_GIA', 'align': 'left' },
            { 'name': 'THANH_TIEN', 'align': 'left' },
            { 'name': 'MUC_HUONG', 'align': 'center' },
            { 'name': 'T_NGUON KHAC', 'align': 'left' },
            { 'name': 'T_BNTT', 'align': 'right' },
            { 'name': 'T_BHTT', 'align': 'right' },
            { 'name': 'T_BNCCT', 'align': 'right' },
            { 'name': 'T_NGOAIDS', 'align': 'right' },
            { 'name': 'MA_KHOA', 'align': 'center' },
            { 'name': 'MA_BAC_SI', 'align': 'left' },
            { 'name': 'MA_BENH', 'align': 'left' },
            { 'name': 'NGAY_YL', 'align': 'center' },
            { 'name': 'MA_PTTT', 'align': 'center' }
        ]
        
        self.xml3 = [
            { 'name': 'STT', 'align': 'center' },
            { 'name': 'MA_DICH_VU', 'align': 'left' },
            { 'name': 'MA_VAT_TU', 'align': 'left' },
            { 'name': 'MA_NHOM', 'align': 'center' },
            { 'name': 'GOI_VTYT', 'align': 'center' },
            { 'name': 'TEN_VAT_TU', 'align': 'left' },
            { 'name': 'TEN_DICH_VU', 'align': 'left' },
            { 'name': 'DON_VI_TINH', 'align': 'center' },
            { 'name': 'PHAM_VI', 'align': 'center' },
            { 'name': 'SO_LUONG', 'align': 'right' },
            { 'name': 'DON_GIA', 'align': 'lrighteft' },
            { 'name': 'TT_THAU', 'align': 'left' },
            { 'name': 'TYLE_TT', 'align': 'center' },
            { 'name': 'THANH_TIEN', 'align': 'right' },
            { 'name': 'T_TRANTT', 'align': 'right' },
            { 'name': 'MUC_HUONG', 'align': 'center' },
            { 'name': 'T_NGUONKHAC', 'align': 'right' },
            { 'name': 'T_BNTT', 'align': 'right' },
            { 'name': 'T_BHTT', 'align': 'right' },
            { 'name': 'T_BNCCT', 'align': 'right' },
            { 'name': 'T_NGOAlDS', 'align': 'right' },
            { 'name': 'MA_KHOA', 'align': 'center' },
            { 'name': 'MA_GIUONG', 'align': 'center' },
            { 'name': 'MA_BAC_SI', 'align': 'left' },
            { 'name': 'MA_BENH', 'align': 'left' },
            { 'name': 'NGAY_YL', 'align': 'center' },
            { 'name': 'NGAY_KQ', 'align': 'center' },
            { 'name': 'MA_PTTT', 'align': 'center' }
        ]
        
        self.xml4 = [
            { 'name': 'STT', 'align': 'center' },
            { 'name': 'MA_DICH_VU', 'align': 'left' },
            { 'name': 'MA_CHI_SO', 'align': 'center' },
            { 'name': 'TEN_CHI_SO', 'align': 'left' },
            { 'name': 'GIA_TRI', 'align': 'center' },
            { 'name': 'MA_MAY', 'align': 'left' },
            { 'name': 'MO_TA', 'align': 'left' },
            { 'name': 'KET_LUAN', 'align': 'left' },
            { 'name': 'NGAY_KQ', 'align': 'center' }
        ]
        
        self.xml5 = [
            { 'name': 'STT', 'align': 'center' },
            { 'name': 'DIEN_BIEN', 'align': 'left' },
            { 'name': 'HOI_CHAN', 'align': 'left' },
            { 'name': 'PHAU_THUAT', 'align': 'left' },
            { 'name': 'NGAY_YL', 'align': 'center' }
        ]
        
class XMLTable_130():
    def __init__(self):
        self.xml1 = [
            { 'name': 'STT', 'align': 'left' },
            { 'name': 'MA_BN', 'align': 'left' },
            { 'name': 'HO_TEN', 'align': 'left' },
            { 'name': 'SO_CCCD', 'align': 'left' },
            { 'name': 'NGAY_SINH', 'align': 'left' },
            { 'name': 'GIOI_TINH', 'align': 'left' },
            { 'name': 'MA_QUOCTICH', 'align': 'left' },
            { 'name': 'MA_DANTOC', 'align': 'left' },
            { 'name': 'MA_NGHE_NGHIEP', 'align': 'left' },
            { 'name': 'DIA_CHI', 'align': 'left' },
            { 'name': 'MATINH_CU_TRU', 'align': 'left' },
            { 'name': 'MAHUYEN_CU_TRU', 'align': 'left' },
            { 'name': 'MAXA_CU_TRU', 'align': 'left' },
            { 'name': 'DIEN_THOAI', 'align': 'left' },
            { 'name': 'MA_THE_BHYT', 'align': 'left' },
            { 'name': 'MA_DKBD', 'align': 'left' },
            { 'name': 'GT_THE_TU', 'align': 'left' },
            { 'name': 'GT_THE_DEN', 'align': 'left' },
            { 'name': 'NGAY_MIEN_CCT', 'align': 'left' },
            { 'name': 'LY_DO_VV', 'align': 'left' },
            { 'name': 'LY_DO_VNT', 'align': 'left' },
            { 'name': 'MA_LY_DO_VNT', 'align': 'left' },
            { 'name': 'CHAN_DOAN_VAO', 'align': 'left' },
            { 'name': 'CHAN_DOAN_RV', 'align': 'left' },
            { 'name': 'MA_BENH_CHINH', 'align': 'left' },
            { 'name': 'MA_BENH_KT', 'align': 'left' },
            { 'name': 'MA_BENH_YHCT', 'align': 'left' },
            { 'name': 'MA_PTTT_QT', 'align': 'left' },
            { 'name': 'MA_DOITUONG_KCB', 'align': 'left' },
            { 'name': 'MA_NOI_DI', 'align': 'left' },
            { 'name': 'MA_NOI_DEN', 'align': 'left' },
            { 'name': 'MA_TAI_NAN', 'align': 'left' },
            { 'name': 'NGAY_VAO', 'align': 'left' },
            { 'name': 'NGAY_VAO_NOI_TRU', 'align': 'left' },
            { 'name': 'NGAY_RA', 'align': 'left' },
            { 'name': 'GIAY_CHUYEN_TUY EN', 'align': 'left' },
            { 'name': 'SO_NGAY_DTRI', 'align': 'left' },
            { 'name': 'PP_DIEU_TRI', 'align': 'left' },
            { 'name': 'KET_QUA_DTRI', 'align': 'left' },
            { 'name': 'MA_LOAI_RV', 'align': 'left' },
            { 'name': 'GHI_CHU', 'align': 'left' },
            { 'name': 'NGAY_TTOAN', 'align': 'left' },
            { 'name': 'T_THUOC', 'align': 'left' },
            { 'name': 'T_VTYT', 'align': 'left' },
            { 'name': 'T_TONGCHI_BV', 'align': 'left' },
            { 'name': 'T_TONGCHI_BH', 'align': 'left' },
            { 'name': 'T_BNTT', 'align': 'left' },
            { 'name': 'T_BNCCT', 'align': 'left' },
            { 'name': 'T_BHTT', 'align': 'left' },
            { 'name': 'T_NGUONKHAC', 'align': 'left' },
            { 'name': 'T_BHTT_GDV', 'align': 'left' },
            { 'name': 'NAM_QT', 'align': 'left' },
            { 'name': 'THANG_QT', 'align': 'left' },
            { 'name': 'MA_LOAI_KCB', 'align': 'left' },
            { 'name': 'MA_KHOA', 'align': 'left' },
            { 'name': 'MA_CSKCB', 'align': 'left' },
            { 'name': 'MA_KHUVUC', 'align': 'left' },
            { 'name': 'CAN_NANG', 'align': 'left' },
            { 'name': 'CAN_NANG_CON', 'align': 'left' },
            { 'name': 'NAM_NAM_LIEN_TUC', 'align': 'left' },
            { 'name': 'NGAY_TAI_KHAM', 'align': 'left' },
            { 'name': 'MA_HSBA', 'align': 'left' },
            { 'name': 'MA_TTDV', 'align': 'left' },
            { 'name': 'DU_PHONG', 'align': 'left' }
        ]

        self.xml2 = [
            {'name':'STT', 'align':'center'},
            {'name':'MA_THUOC', 'align':'left'},
            {'name':'MA_PP_CHEBIEN', 'align':'left'},
            {'name':'MA_CSKCB_THUOC', 'align':'left'},
            {'name':'MA_NHOM', 'align':'center'},
            {'name':'TEN_THUOC', 'align':'left'},
            {'name':'DON_VI_TINH', 'align':'center'},
            {'name':'HAM_LUONG', 'align':'left'},
            {'name':'DUONG_DUNG', 'align':'center'},
            {'name':'DANG_BAO_CHE', 'align':'left'},
            {'name':'LIEU_DUNG', 'align':'left'},
            {'name':'CACH_DUNG', 'align':'left'},
            {'name':'SO_DANG_KY', 'align':'left'},
            {'name':'TT_THAU', 'align':'left'},
            {'name':'PHAM_VI', 'align':'center'},
            {'name':'TYLE_TT_BH', 'align':'center'},
            {'name':'SO_LUONG', 'align':'left'},
            {'name':'DON_GIA', 'align':'right'},
            {'name':'THANH_TIEN_BV', 'align':'right'},
            {'name':'THANH_TIEN_BH', 'align':'right'},
            {'name':'T_NGUONKHAC_NSNN', 'align':'right'},
            {'name':'T_NGUONKHAC_VTNN', 'align':'right'},
            {'name':'T_NGUONKHAC_VTTN', 'align':'right'},
            {'name':'T_NGUONKHAC_CL', 'align':'right'},
            {'name':'T_NGUONKHAC', 'align':'right'},
            {'name':'MUC_HUONG', 'align':'center'},
            {'name':'T_BNTT', 'align':'right'},
            {'name':'T_BNCCT', 'align':'right'},
            {'name':'T_BHTT', 'align':'right'},
            {'name':'MA_KHOA', 'align':'center'},
            {'name':'MA_BAC_SI', 'align':'center'},
            {'name':'MA_DICH_VU', 'align':'left'},
            {'name':'NGAY_YL', 'align':'center'},
            {'name':'MA_PTTT', 'align':'center'},
            {'name':'NGUON_CTRA', 'align':'center'},
            {'name':'VET_THUONG_TP', 'align':'left'},
            {'name':'DU_PHONG', 'align':'left'}
        ]

        self.xml3 = [
            { 'name': 'STT', 'align': 'left' },
            { 'name': 'MA_DICH_VU', 'align': 'left' },
            { 'name': 'MA_PTTT_QT', 'align': 'left' },
            { 'name': 'MA_VAT_TU', 'align': 'left' },
            { 'name': 'MA_NHOM', 'align': 'left' },
            { 'name': 'GOI_VTYT', 'align': 'left' },
            { 'name': 'TEN_VAT_TU', 'align': 'left' },
            { 'name': 'TEN_DICH_VU', 'align': 'left' },
            { 'name': 'MA_XANG_DAU', 'align': 'left' },
            { 'name': 'DON_VI_TINH', 'align': 'left' },
            { 'name': 'PHAM_VI', 'align': 'left' },
            { 'name': 'SO_LUONG', 'align': 'left' },
            { 'name': 'DON_GIA_BV', 'align': 'left' },
            { 'name': 'DON_GIA_BH', 'align': 'left' },
            { 'name': 'TT_THAU', 'align': 'left' },
            { 'name': 'TYLE_TT_DV', 'align': 'left' },
            { 'name': 'TYLE_TT_BH', 'align': 'left' },
            { 'name': 'THANH_TIEN_BV', 'align': 'left' },
            { 'name': 'THANH_TIEN_BH', 'align': 'left' },
            { 'name': 'T_TRANTT', 'align': 'left' },
            { 'name': 'MUC_HUONG', 'align': 'left' },
            { 'name': 'T_NGUONKHAC_NSNN', 'align': 'left' },
            { 'name': 'T_NGUONKHAC_VTNN', 'align': 'left' },
            { 'name': 'T_NGUONKHAC_VTTN', 'align': 'left' },
            { 'name': 'T_NGUONKHAC_CL', 'align': 'left' },
            { 'name': 'T_NGUONKHAC', 'align': 'left' },
            { 'name': 'T_BNTT', 'align': 'left' },
            { 'name': 'T_BNCCT', 'align': 'left' },
            { 'name': 'T_BHTT', 'align': 'left' },
            { 'name': 'MA_KHOA', 'align': 'left' },
            { 'name': 'MA_GIUONG', 'align': 'left' },
            { 'name': 'MA_BAC_SI', 'align': 'left' },
            { 'name': 'NGUOI_THUC_HIEN', 'align': 'left' },
            { 'name': 'MA_BENH', 'align': 'left' },
            { 'name': 'MA_BENH_YHCT', 'align': 'left' },
            { 'name': 'NGAY_YL', 'align': 'left' },
            { 'name': 'NGAY_TH_YL', 'align': 'left' },
            { 'name': 'NGAY_KQ', 'align': 'left' },
            { 'name': 'MA_PTTT', 'align': 'left' },
            { 'name': 'VET_THUONG_TP', 'align': 'left' },
            { 'name': 'PP_VO_CAM', 'align': 'left' },
            { 'name': 'VI_TRI_TH_DVKT', 'align': 'left' },
            { 'name': 'MA_MAY', 'align': 'left' },
            { 'name': 'MA_HIEU_SP', 'align': 'left' },
            { 'name': 'TAI_SU_DUNG', 'align': 'left' },
            { 'name': 'DU_PHONG', 'align': 'left' }
        ]

        self.xml4 = [
            {'name':'STT', 'align':'left'},
            {'name':'MA_DICH_VU', 'align':'left'},
            {'name':'MA_CHI_SO', 'align':'left'},
            {'name':'TEN_CHI_SO', 'align':'left'},
            {'name':'GIA_TRI', 'align':'left'},
            {'name':'DON_VI_DO', 'align':'left'},
            {'name':'MO_TA', 'align':'left'},
            {'name':'KET_LUAN', 'align':'left'},
            {'name':'NGAY_KQ', 'align':'left'},
            {'name':'MA_BS_DOC_KQ', 'align':'left'},
            {'name':'DU_PHONG', 'align':'left'}
        ]

        self.xml5 = [
            { 'name': 'STT', 'align': 'left' },
            { 'name': 'DIEN_BIEN_LS', 'align': 'left' },
            { 'name': 'GIAI_DOAN_BENH', 'align': 'left' },
            { 'name': 'HOI_CHAN', 'align': 'left' },
            { 'name': 'PHAU_THUAT', 'align': 'left' },
            { 'name': 'THOI_DIEM_DBLS', 'align': 'left' },
            { 'name': 'NGUOI_THUC_HIEN', 'align': 'left' },
            { 'name': 'DU_PHONG', 'align': 'left' }
            
        ]
        
        
    